spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE


logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
